//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chart
    {
        public int c_id { get; set; }
        public string chart_name { get; set; }
        public string chart_description { get; set; }
        public Nullable<int> chart_weight { get; set; }
        public Nullable<int> t_id { get; set; }
    
        public virtual trainee trainee { get; set; }
    }
}
