//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int eq_id { get; set; }
        public string eq_name { get; set; }
        public Nullable<int> eq_tra_id { get; set; }
    
        public virtual trainer trainer { get; set; }
    }
}
