//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class physcial_details
    {
        public int p_id { get; set; }
        public Nullable<double> T_Hieght { get; set; }
        public Nullable<double> T_Weight { get; set; }
        public Nullable<int> T_Age { get; set; }
        public int traine_id { get; set; }
        public Nullable<int> tt_id { get; set; }
        public Nullable<int> Mh_id { get; set; }
        public Nullable<int> GB_id { get; set; }
        public Nullable<int> GEt_id { get; set; }
        public Nullable<int> to_eq_id { get; set; }
    
        public virtual Gym_Branch Gym_Branch { get; set; }
        public virtual Gym_Equipment_type Gym_Equipment_type { get; set; }
        public virtual Membership_History Membership_History { get; set; }
        public virtual trainee trainee { get; set; }
        public virtual Timetable Timetable { get; set; }
        public virtual type_of_equipment1 type_of_equipment1 { get; set; }
    }
}
