//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_trainer
    {
        public int s_tr_id { get; set; }
        public Nullable<int> t_id { get; set; }
        public Nullable<int> trainer_id { get; set; }
    
        public virtual trainer trainer { get; set; }
        public virtual trainee trainee { get; set; }
    }
}
