//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainee_details
    {
        public int d_id { get; set; }
        public Nullable<double> waist { get; set; }
        public Nullable<double> thighs { get; set; }
        public Nullable<double> arms { get; set; }
        public Nullable<double> chest { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> trainee_id { get; set; }
    
        public virtual trainee trainee { get; set; }
    }
}
